### ISSUE TITLE
SodiumCore 

### ISSUE THREAD

**Issue by sweetSneak** [tangramproject/Cypher#12]
```
System.TypeInitializationException: The type initializer for 'Sodium.SodiumCore' threw an exception. ---> System.DllNotFoundException: Unable to load DLL 'libsodium' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at Sodium.SodiumLibrary.sodium_init()
   at Sodium.SodiumCore.Init()
   at Sodium.SodiumCore..cctor()
   --- End of inner exception stack trace ---
   at TangramCypher.Helper.LibSodium.Cryptography.RandomBytes(Int32 bytes) in C:\Users\asdfjkl;\Cypher\Helper\LibSodium\Cryptography.cs:line 120
   at TangramCypher.ApplicationLayer.Wallet.WalletService.NewID(Int32 bytes) in C:\Users\asdfjkl;\Cypher\ApplicationLayer\Wallet\WalletService.cs:line 168
   at TangramCypher.ApplicationLayer.Wallet.WalletService.CreateWallet()
   at TangramCypher.ApplicationLayer.Commands.Wallet.WalletCreateCommand.Execute() in C:\Users\asdfjkl;\Cypher\ApplicationLayer\Commands\Wallet\WalletCreateCommand.cs:line 31
   at TangramCypher.ApplicationLayer.Commands.CommandService.Execute(String[] args) in C:\Users\asdfjkl;\Cypher\ApplicationLayer\Commands\CommandService.cs:line 126
   at TangramCypher.ApplicationLayer.Commands.CommandService.InteractiveCliLoop() in C:\Users\asdfjkl;\Cypher\ApplicationLayer\Commands\CommandService.cs:line 168
```

**Comment by pingpongsneak** [comment]
Fresh windows installed.. was missing VC++.
Download here:
https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads
